name: GitHub Actions Demo
on: push
jobs:
Explore-GitHub_Actions:
runs-on:ubuntu-latest
steps:
- name: print the triggreing event 
run : echo "the jop was triggered by ${{github.event_name}}"
-name Print the OS of the runner
run : echothis jop is running on a ${{runner.os}} server"
